exports_files(["Makefile"])

filegroup(
    name = "bifrost_srcs",
    srcs = glob(
        ["**"],
        exclude = [
            "BUILD.bazel",
            "**/*.bzl",
            "**/*.mk",
            "**/*.bp",
            ".git/**",
        ],
    ),
    visibility = ["//visibility:public"],
)
